### PR TITLE
add condition to fix negative value display

### LINKED ISSUE #20: [BUG]Negative values not exported correctly
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

---

Issue occurred when generating CSV file from a table in Discover. Negative numbers appear in the csv with an extra `'` in front of them. This is what it looks like:

Negative value | Positive value
-- | --
'-47 | 520
'-15 | 475

For reference, this field is of type `number`

This issue is submitted by @melvinkokxw
https://github.com/opendistro-for-elasticsearch/kibana-reports/issues/344

### PR DESCRIPTION
**Pull request by davidcui-amzn**
Signed-off-by: David Cui <davidcui@amazon.com>

### Description
Fixes negative value display for CSV to correctly display without a leading `'`

### Issues Resolved
#20 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: dashboards-reports/server/routes/utils/dataReportHelpers.ts [hunk 1]
```diff
@@ -236,7 +235,7 @@ function sanitize(doc: any) {
   for (const field in doc) {
     if (
       doc[field].toString().startsWith('+') ||
-      doc[field].toString().startsWith('-') ||
+      (doc[field].toString().startsWith('-') && typeof doc[field] != "number") ||
```
Comment (joshuali925) [inline dashboards-reports/server/routes/utils/dataReportHelpers.ts:238]: shouldn't change anything but could you use !== instead of !=

**Review by joshuali925 — APPROVED** [review]

**Review by zhongnansu — APPROVED** [review]
LGTM
